import { createDecipheriv } from "node:crypto";

const ALGORITHM = "aes-256-gcm";
const AUTH_TAG_LENGTH = 16;
const EXPECTED_VERSION = "v1";

function getEncryptionKey(): Buffer {
  const rawKey = process.env.PROVIDER_KEY_ENCRYPTION_KEY;
  if (!rawKey) {
    throw new Error(
      "Missing PROVIDER_KEY_ENCRYPTION_KEY environment variable.",
    );
  }

  let key: Buffer;
  try {
    key = Buffer.from(rawKey, "base64");
  } catch {
    throw new Error("PROVIDER_KEY_ENCRYPTION_KEY must be valid base64.");
  }

  if (key.length !== 32) {
    throw new Error(
      "PROVIDER_KEY_ENCRYPTION_KEY must decode to 32 bytes (AES-256 key).",
    );
  }

  return key;
}

function assertServerOnly() {
  if (typeof window !== "undefined") {
    throw new Error("Decryption must only run on the server.");
  }
}

function parsePayload(payload: string) {
  const parts = payload.split(":");
  if (parts.length !== 4) {
    throw new Error("Invalid encrypted payload format.");
  }

  const [version, ivPart, tagPart, cipherPart] = parts;
  if (version !== EXPECTED_VERSION) {
    throw new Error("Unsupported encrypted payload version.");
  }

  let iv: Buffer;
  let authTag: Buffer;
  let ciphertext: Buffer;
  try {
    iv = Buffer.from(ivPart, "base64url");
    authTag = Buffer.from(tagPart, "base64url");
    ciphertext = Buffer.from(cipherPart, "base64url");
  } catch {
    throw new Error("Encrypted payload is not valid base64url.");
  }

  if (iv.length !== 12) {
    throw new Error("Invalid IV length in encrypted payload.");
  }
  if (authTag.length !== AUTH_TAG_LENGTH) {
    throw new Error("Invalid auth tag length in encrypted payload.");
  }
  if (ciphertext.length === 0) {
    throw new Error("Encrypted payload has no ciphertext.");
  }

  return { iv, authTag, ciphertext };
}

/**
 * Decrypts payloads generated by encryptProviderKey().
 */
export function decryptProviderKey(encryptedPayload: string): string {
  assertServerOnly();

  if (!encryptedPayload || !encryptedPayload.trim()) {
    throw new Error("Encrypted payload cannot be empty.");
  }

  const key = getEncryptionKey();
  const { iv, authTag, ciphertext } = parsePayload(encryptedPayload.trim());

  try {
    const decipher = createDecipheriv(ALGORITHM, key, iv, {
      authTagLength: AUTH_TAG_LENGTH,
    });
    decipher.setAuthTag(authTag);

    const plaintext = Buffer.concat([
      decipher.update(ciphertext),
      decipher.final(),
    ]).toString("utf8");

    if (!plaintext) {
      throw new Error("Decrypted payload is empty.");
    }

    return plaintext;
  } catch {
    throw new Error("Failed to decrypt provider key.");
  }
}
